AllCops:
  TargetRubyVersion: 2.4

Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*
    - npmdc.gemspec

# FIXME:

Metrics/ClassLength:
  Exclude:
    - lib/npmdc/checker.rb

Metrics/AbcSize:
  Exclude:
    - lib/npmdc/checker.rb

Metrics/LineLength:
  Exclude:
    - lib/npmdc/checker.rb

Metrics/CyclomaticComplexity:
  Exclude:
    - lib/npmdc/checker.rb

Metrics/PerceivedComplexity:
  Exclude:
    - lib/npmdc/checker.rb

Metrics/MethodLength:
  Exclude:
    - lib/npmdc/checker.rb
