sudo: false
language: ruby
cache: bundler
matrix:
  include:
    - rvm: 2.3.3
      gemfile: gemfiles/rails42.gemfile
    - rvm: 2.3.3
      gemfile: gemfiles/rails5.gemfile

before_install: gem install bundler -v 1.13.6
